name: nonreg-tests
permissions:
  contents: read
  pull-requests: write

on:
  # Activate the workflow at each push on dev branch
  push:
    branches: [ master ]
  # Activate the workflow at each pull request on dev branch
  pull_request:
    branches: [ master ]
  # Permit manual trigger
  workflow_dispatch:

jobs:
  call-macos-latest:
    uses: ./.github/workflows/nonreg-tests_macos-latest.yml
  call-windows-latest:
    uses: ./.github/workflows/nonreg-tests_windows-latest.yml
  call-ubuntu-latest:
    uses: ./.github/workflows/nonreg-tests_ubuntu-latest.yml
  call-format:
    uses: ./.github/workflows/format.yml
