name: nonreg-tests_ubuntu-latest

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [
          "3.11",
          "3.12",
          "3.13",
        ]
    env:
      QT_QPA_PLATFORM: offscreen

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true

      - name: Setup Python Version
        run: |
          pixi add python==${{ matrix.py }} numpy -p linux-64

      - name: Create & configure Smil build directory
        run: |
          mkdir build && cd build
          pixi run cmake \
            -DBUILD_TEST=ON \
            -DWRAP_PYTHON=ON \
            -DUSE_NUMPY=ON \
            $GITHUB_WORKSPACE
        env:
          CMAKE_GENERATOR: Ninja
          CMAKE_BUILD_TYPE: Release

      - name: Build Smil
        run: |
          cd build
          pixi run cmake --build . --parallel 3

      - name: Install Smil
        run: |
          cd build
          sudo cmake --build . --target install
          sudo mv /usr/local/lib/Smil/_*.so /usr/local/lib/Smil/smilPython

      - name: Execute non-regression tests and benchmarks
        run: |
          cd build
          pixi run ctest
        env:
          PYTHONPATH: /usr/local/lib/Smil
        continue-on-error: true
