name: publish_python_manylinux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.2.1

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/${{ matrix.image }}
    strategy:
      matrix:
        # Python version
        python: [
          # Double quote for version is needed otherwise 3.10 => 3.1
            "cp39-cp39",
            "cp310-cp310",
            "cp311-cp311",
            "cp312-cp312",
            "cp313-cp313",
            "cp314-cp314"
          ]
        image: [
           manylinux_2_28_x86_64
        ]
        os: [
           ubuntu-latest,
        ]

    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v7
      with:
        name: cibw-wheels-${{ matrix.os }}

    - name: Register the python version
      run: |
        echo "/opt/python/${{ matrix.python }}/bin" >> $GITHUB_PATH

    - name: Setup uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{env.PYTHON_VERSION}}
        activate-environment: true

    - name: Install Python package
      run: |
        uv pip install "./$(ls *.whl)"

    - name: Test installed package
      run: |
        python -c "import smilPython as sp"

    - name: Test Python scripts
      run: |
        cp -r images/* doc/demos/python
        cd doc/demos/python/
        python base_graph.py
        python benchs.py
        python blob_measures.py
        python constrained_watershed.py
        python copy_crop.py
        python example-3D-image-rotate.py
        python example-areathreshold.py
        python example-asfclose.py
        python example-bresenham.py
        python example-default-se.py
        python example-distance-geodesic.py
        python example-gaussian-filter.py
        python example-horiz-convolve.py
        python example-imagefileinfo-print.py
        python example-inertia-matrix.py
        python example-intro-blobs.py
        python example-point-minus.py
        python example-read.py
        python example-readRAW.py
        python extinction_values.py
        python first-program.py
        python hit_or_miss.py
        python loop-input.py
        python loop-sleep.py
        python multichannel_operations.py
        python numpy_array.py
        python numpy_np2image.py
        python numpy_np2sp.py
        python numpy_sp2np2sp.py
        python numpy_sp2np.py
        python operators.py
        python skiz.py
        python thresholds.py
        python x_image_01.py
      shell: bash
      env:
        QT_QPA_PLATFORM: offscreen
