name: publish_ubuntu-latest
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.67.2
          run-install: false

      - name: Generate conda packages
        run: |
          pixi build

      - uses: actions/upload-artifact@v7
        with:
          name: smil-conda
          path: ./*.conda
