name: publish_manylinux
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [publish_manylinux]

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/${{ matrix.image }}
    strategy:
      matrix:
        python: [
          "cp310-cp310",
          ]
        image: [
           manylinux_2_28_x86_64
        ]

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y \
            libcurl-devel \
            sudo

      - name: Register the python version
        run: |
          echo "/opt/python/${{ matrix.python }}/bin" >> $GITHUB_PATH

      - name: Install python dependencies
        run: |
          pip install swig numpy build ninja wheel

      - name: Checkout zlib
        uses: actions/checkout@v5
        with:
          repository: "madler/zlib"
          ref: "v1.3.1"
          path: "zlib-src"

      - name: Build & install static zlib
        run: |
          cmake -S zlib-src -B zlib-build \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build zlib-build --target install

      - name: Checkout libpng
        uses: actions/checkout@v5
        with:
          repository: "pnggroup/libpng"
          ref: "v1.6.50"
          path: "libpng-src"

      - name: Build & install static libpng
        run: |
          cmake -S libpng-src -B libpng-build \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DPNG_SHARED=OFF \
            -DPNG_TESTS=OFF \
            -DZLIB_ROOT=$GITHUB_WORKSPACE/deps \
            -DZLIB_USE_STATIC_LIBS=ON \
            -DPNG_SHARED=OFF \
            -DPNG_TOOLS=OFF \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build libpng-build --target install

      - name: Checkout libjpeg-turbo
        uses: actions/checkout@v5
        with:
          repository: "libjpeg-turbo/libjpeg-turbo"
          ref: "3.1.3"
          path: "libjpeg-turbo-src"

      - name: Build & install static libjpeg-turbo
        run: |
          cmake -S libjpeg-turbo-src -B libjpeg-build \
              -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
              -DBUILD_SHARED_LIBS=OFF \
              -DENABLE_SHARED=OFF \
              -DENABLE_STATIC=ON \
              -DWITH_TESTS=OFF \
              -DWITH_TOOLS=OFF \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build libjpeg-build --target install

      - name: Checkout libtiff
        run: |
          git clone --depth 1 https://gitlab.com/libtiff/libtiff.git libtiff-src

      - name: Build & install static libtiff
        run: |
          cmake -S libtiff-src -B libtiff-build \
              -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
              -DBUILD_SHARED_LIBS=OFF \
              -Djpeglib=ON \
              -Dzlib=ON \
              -Dtiff-static=ON \
              -Dtiff-contrib=OFF \
              -Dtiff-docs=OFF \
              -Dtiff-tests=OFF \
              -Dtiff-tools=OFF \
              -DJPEG_INCLUDE_DIR=$GITHUB_WORKSPACE/deps/include \
              -DJPEG_LIBRARY=$GITHUB_WORKSPACE/deps/lib/jpeg-static.lib \
              -DZLIB_INCLUDE_DIR=$GITHUB_WORKSPACE/deps/include \
              -DZLIB_LIBRARY=$GITHUB_WORKSPACE/deps/lib/zlibstatic.lib \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build libtiff-build --target install

      - name: Checkout freetype
        run: |
          git clone --depth 1 -b VER-2-14-1 https://gitlab.freedesktop.org/freetype/freetype.git freetype-src

      - name: Build & install static freetype
        run: |
          cmake -S freetype-src -B freetype-build \
              -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
              -DBUILD_SHARED_LIBS=OFF \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build freetype-build --target install

      - name: Create & configure Smil build directory
        run: |
          cmake -S . -B build \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DBUILD_TEST=ON \
            -DWRAP_PYTHON=ON \
            -DUSE_OPTIMIZATION=OFF \
            -DUSE_QT=OFF \
            -DPNG_ROOT=$GITHUB_WORKSPACE/deps \
            -DJPEG_ROOT=$GITHUB_WORKSPACE/deps \
            -DTIFF_INCLUDE_DIR=$GITHUB_WORKSPACE/deps/include \
            -DTIFF_LIBRARY=$GITHUB_WORKSPACE/deps/lib64/libtiff.a \
            -DFREETYPE_INCLUDE_DIRS=$GITHUB_WORKSPACE/deps/include/freetype2 \
            -DFREETYPE_LIBRARY=$GITHUB_WORKSPACE/deps/lib64/libfreetype.a

      - name: Build Smil
        run: |
          cmake --build build --config Release
          ldd build/lib/_smilIOPython.so

      - name: Build Python package
        run: |
          cmake --build build --config Release --target python_package

      - name: Build wheel from Python package
        run: |
          cd build/python
          python -m build --wheel -C="--build-option=--plat-name=${{ matrix.image }}"
          python -m wheel tags --abi-tag=abi3 dist/*.whl

      - uses: actions/upload-artifact@v4
        with:
          name: linux-python-package-x64
          path: build/python/dist/*abi3*.whl

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        py: [
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14",
          ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: linux-python-package-x64

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.py }}
          activate-environment: true

      - name: Install Python package
        run: |
          uv pip install "$(ls *.whl)"

      - name: Test Python import
        run: |
          python -c 'import smilPython as sp; dir(sp)'

      - name: Test Python scripts
        run: |
          cp -r images/* doc/demos/python
          cd doc/demos/python/
          python base_graph.py
          python benchs.py
          python blob_measures.py
          python constrained_watershed.py
          python copy_crop.py
          python example-3D-image-rotate.py
          python example-areathreshold.py
          python example-asfclose.py
          python example-bresenham.py
          python example-default-se.py
          python example-distance-geodesic.py
          python example-gaussian-filter.py
          python example-horiz-convolve.py
          python example-imagefileinfo-print.py
          python example-inertia-matrix.py
          python example-intro-blobs.py
          python example-point-minus.py
          python example-read.py
          python example-readRAW.py
          python extinction_values.py
          python first-program.py
          python hit_or_miss.py
          python loop-input.py
          python loop-sleep.py
          python multichannel_operations.py
          python numpy_array.py
          python numpy_np2image.py
          python numpy_np2sp.py
          python numpy_sp2np2sp.py
          python numpy_sp2np.py
          python operators.py
          python skiz.py
          python thresholds.py
          python x_image_01.py
