name: publish_conda
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-large, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.67.2
          run-install: false

      - name: Generate conda packages
        run: |
          pixi build

      - uses: actions/upload-artifact@v7
        with:
          name: smil-conda-${{ matrix.os }}
          path: ./*.conda

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-large, windows-latest]
        python: [py310, py311, py312, py313, py314]
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.67.2
          run-install: false

      - uses: actions/download-artifact@v7
        with:
          name: smil-conda-${{ matrix.os }}

      - name: Install conda package
        run: |
          rm -f pixi*
          pixi init
          pixi add $PWD/smil-*-${{ matrix.python }}*.conda
        shell: bash

      - name: Test installed package
        run: |
          pixi run python -c "import smilPython as sp"

      - name: Test Python scripts
        run: |
          cp -r images/* doc/demos/python
          cd doc/demos/python/
          pixi run python base_graph.py
          pixi run python benchs.py
          pixi run python blob_measures.py
          pixi run python constrained_watershed.py
          pixi run python copy_crop.py
          pixi run python example-3D-image-rotate.py
          pixi run python example-areathreshold.py
          pixi run python example-asfclose.py
          pixi run python example-bresenham.py
          pixi run python example-default-se.py
          pixi run python example-distance-geodesic.py
          pixi run python example-gaussian-filter.py
          pixi run python example-horiz-convolve.py
          pixi run python example-imagefileinfo-print.py
          pixi run python example-inertia-matrix.py
          pixi run python example-intro-blobs.py
          pixi run python example-point-minus.py
          pixi run python example-read.py
          pixi run python example-readRAW.py
          pixi run python extinction_values.py
          pixi run python first-program.py
          pixi run python hit_or_miss.py
          pixi run python loop-input.py
          pixi run python loop-sleep.py
          pixi run python multichannel_operations.py
          pixi run python numpy_array.py
          pixi run python numpy_np2image.py
          pixi run python numpy_np2sp.py
          pixi run python numpy_sp2np2sp.py
          pixi run python numpy_sp2np.py
          pixi run python operators.py
          pixi run python skiz.py
          pixi run python thresholds.py
          pixi run python x_image_01.py
        shell: bash
        env:
          QT_QPA_PLATFORM: offscreen
