name: publish_python_manylinux

on:
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  workflow_dispatch:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true

env:
  CMAKE_BUILD_TYPE : Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/${{ matrix.image }}
    strategy:
      matrix:
        py: [
          "cp39-cp39",
          "cp310-cp310",
          "cp311-cp311",
          "cp312-cp312",
          "cp313-cp313",
        ]
        image: [
           manylinux_2_28_x86_64
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y \
            sudo \
            libcurl-devel \
            freetype-devel \
            libtiff-devel \
            qt5-qtbase-devel \
            qwt-qt5-devel \
            ninja-build

      - name: Fetch libpng source code
        uses: actions/checkout@v4
        with:
          repository: pnggroup/libpng
          ref: v1.6.49
          path: libpng

      - name: Build & install libpng
        run: |
          cd libpng
          mkdir build && cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DPNG_SHARED=OFF \
            -DPNG_TOOLS=OFF \
            ..
          cmake --build . --parallel 3
          sudo cmake --build . --target install

      - name: Setup Python Version
        run: |
          echo "/opt/python/${{ matrix.py }}/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python3 -m pip install numpy swig

      - name: Create & configure Smil build directory
        run: |
          mkdir build && cd build
          cmake \
            -DBUILD_TEST=ON \
            -DWRAP_PYTHON=ON \
            -DUSE_NUMPY=ON \
            $GITHUB_WORKSPACE
        env:
          CMAKE_GENERATOR: Ninja

      - name: Build Smil
        run: |
          cd build
          cmake --build . --parallel 3

      - name: Install Smil
        run: |
          cd build
          sudo cmake --build . --target install
          sudo mv /usr/local/lib/Smil/_*.so /usr/local/lib/Smil/smilPython

      - name: Execute non-regression tests and benchmarks
        run: |
          cd build
          ctest
        env:
          PYTHONPATH: /usr/local/lib/Smil
        continue-on-error: true
